[versions]
kotlin = "1.5.30"
spring-boot = "2.7.4"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

mockk = { module = "io.mockk:mockk", version = "1.12.8"}

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-dependency-management = {id = "io.spring.dependency-management", version = "1.0.14.RELEASE"}